#!/usr/bin/perl
#
# This file is part of the Echidna framework
#
# Copyright (C) 2010-2012, Edward Fjellskål <edwardfjellskaal@gmail.com>
#                          Eduardo Urias    <windkaiser@gmail.com>
#                          Ian Firns        <firnsy@securixlive.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License Version 2 as
# published by the Free Software Foundation.  You may not use, modify or
# distribute this program under any other version of the GNU General
# Public License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

use warnings;
use strict;

use 5.010;

#
# PERL INCLUDES
#
use Data::Dumper;
use EV;
use Mojo::Server;
use Mojo::Server::Daemon;
use Mojolicious::Commands;

#
# LOCAL INCLUDES
#
use Echidna::Config;

# load configuration
#
my $conf = Echidna::Config->new({
  host => 'localhost',
  port => 6967,
  key  => 'secret',

  passivedns => {
    mode  => 'delete',
    dir   => '/var/log/cxtracker',
    regex => 'stats.*',
    poll  => 10,
  },
});

$conf->parse_command_line( @ARGV );

my $daemon = Mojo::Server::Daemon->new;

my $app = $daemon->build_app('Echidna::Node::Passivedns');
$app->config($conf);
$app->startup_post();
$app->start('daemon', '--listen', $conf->listen);


