#!/usr/bin/env perl

use strict;
use warnings;

use File::Spec;
use File::Basename 'dirname';
use lib join '/', File::Spec->splitdir(dirname(__FILE__)), 'lib';
use lib join '/', File::Spec->splitdir(dirname(__FILE__)), '..', 'lib';

use Mojolicious::Commands;

$ENV{MOJO_APP} = 'NSMF::Web::Server';

Mojolicious::Commands->start;
